using SignalRMVCChat.Models.autoGeneratedContext;
using TelegramBotsWebApplication.Areas.Admin.Service;

namespace SignalRMVCChat.Service
{
    public class DistributionService:GenericService<Distribution>
    {
        public DistributionService(GenericImp<Distribution> impl
        ) : base(impl)
        {
        }
    }
    
    public class MalinfoService:GenericService<MalInfos>
    {
        public MalinfoService(GenericImp<MalInfos> impl
        ) : base(impl)
        {
        }
    }
}