// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using my_webapp.Model;

namespace KhInventoryAuth.Migrations
{
    [DbContext(typeof(KhInventoryDbContext))]
    [Migration("20210213073418_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SignalRMVCChat.Models.autoGeneratedContext.Distribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressVaNameRusta")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("CodeMelli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etehadie")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("F16")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("HomeTelephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaheSahmie")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("MalCount")
                        .HasColumnType("int");

                    b.Property<string>("MeqdareTahviliKG")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("NamVaNameKhanevadegi")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("NodeNahade")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("NoeFaaliat")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("QeymateHarKGbeRIAL")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Shahrestan")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("ShomareOzviateTaavoni")
                        .HasColumnType("float");

                    b.Property<string>("Taavoni")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ZarfiatYaTedadeDamoTiur")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Distribution");
                });

            modelBuilder.Entity("SignalRMVCChat.Models.autoGeneratedContext.MalInfos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DistributionId")
                        .HasColumnType("int");

                    b.Property<string>("Marhale1")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("Marhale2")
                        .HasColumnType("float");

                    b.Property<string>("NameDamdar")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("PKFrom")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("PKTo")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Rusta")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<double?>("TotalCow")
                        .HasColumnType("float");

                    b.Property<double?>("TotalGowMish")
                        .HasColumnType("float");

                    b.Property<double?>("TotalMal")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("MalInfos");
                });

            modelBuilder.Entity("my_webapp.Model.AnimalFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ForTestField")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerCustomerTotalMalQouta")
                        .HasColumnType("int");

                    b.Property<int>("PerUnitPrice")
                        .HasColumnType("int");

                    b.Property<int>("Remain")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AnimalFoods");
                });

            modelBuilder.Entity("my_webapp.Model.AnimalFoodBuy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnimalFoodId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PerUnitPrice")
                        .HasColumnType("int");

                    b.Property<int>("Quan")
                        .HasColumnType("int");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnimalFoodId");

                    b.ToTable("AnimalFoodBuy");
                });

            modelBuilder.Entity("my_webapp.Model.IssueAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnimalFoodId")
                        .HasColumnType("int");

                    b.Property<string>("BankFish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("Quan")
                        .HasColumnType("int");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnimalFoodId");

                    b.HasIndex("PersonId");

                    b.ToTable("IssueAssignments");
                });

            modelBuilder.Entity("my_webapp.Model.AnimalFoodBuy", b =>
                {
                    b.HasOne("my_webapp.Model.AnimalFood", "AnimalFood")
                        .WithMany("AnimalFoodBuys")
                        .HasForeignKey("AnimalFoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("my_webapp.Model.IssueAssignment", b =>
                {
                    b.HasOne("my_webapp.Model.AnimalFood", "AnimalFood")
                        .WithMany("IssueAssignments")
                        .HasForeignKey("AnimalFoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SignalRMVCChat.Models.autoGeneratedContext.Distribution", "Person")
                        .WithMany("IssueAssignments")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
