using SignalRMVCChat.Models.autoGeneratedContext;
using SignalRMVCChat.Service;
using TelegramBotsWebApplication.Areas.Admin.Controllers;

namespace my_webapp.Controllers
{
    
    public class MalinfoController:GenericController<MalInfos>
    {
        public MalinfoController(MalinfoService MalinfoService)
        {
            Service = MalinfoService;
        }
    }
}