using Microsoft.AspNetCore.Mvc;
using my_webapp.Model;
using my_webapp.Service;
using SignalRMVCChat.Models.autoGeneratedContext;
using TelegramBotsWebApplication.Areas.Admin.Models;

namespace my_webapp.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class PersonController:BaseController<Distribution,PersonService>
    {
        public PersonController(PersonService service) : base(service)
        {
        }


        [HttpGet("[action]")]
        public virtual MyDataTableResponse<Person> Search( string searchTerm)
        {
            if (string.IsNullOrEmpty(searchTerm))
            {
                return _service.GetAll();
            }
            var resonse = _service.Search(searchTerm);
                resonse.Status = MyResponseStatus.Success;
                return resonse;
        }
    }
}