using my_webapp.Model;
using TelegramBotsWebApplication.Areas.Admin.Service;

namespace SignalRMVCChat.Models.autoGeneratedContext
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Distribution")]
    public partial class Distribution:EntitySafeDelete
    {

        public int? MalCount { get; set; }
        public List<IssueAssignment> IssueAssignments { get; set; }

        [StringLength(255)]
        public string Etehadie { get; set; }

        [StringLength(255)]
        public string Taavoni { get; set; }

        [StringLength(255)]
        public string Shahrestan { get; set; }

        [StringLength(255)]
        public string NamVaNameKhanevadegi { get; set; }

        public string CodeMelli { get; set; }

        [StringLength(255)]
        public string AddressVaNameRusta { get; set; }

        public string Telephone { get; set; }

        public double? ShomareOzviateTaavoni { get; set; }

        [StringLength(255)]
        public string NoeFaaliat { get; set; }

        public double? ZarfiatYaTedadeDamoTiur { get; set; }

        [StringLength(255)]
        public string NodeNahade { get; set; }

        [StringLength(255)]
        public string MeqdareTahviliKG { get; set; }

        [StringLength(255)]
        public string QeymateHarKGbeRIAL { get; set; }

        [StringLength(255)]
        public string MaheSahmie { get; set; }

        [StringLength(255)]
        public string F16 { get; set; }

        public string HomeTelephone { get; set; }
    }
}
